# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_game_cover_alter_game_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="games/covers/"),
        ),
    ]
