# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_game_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="detailed_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="game",
            name="developer",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
