# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def _make_unique_slug(Developer, name):
    base = (slugify(name) or "developer")[:160]
    slug = base
    index = 2
    while Developer.objects.filter(slug=slug).exists():
        suffix = f"-{index}"
        slug = f"{base[:160 - len(suffix)]}{suffix}"
        index += 1
    return slug


def forwards_copy_developers(apps, schema_editor):
    Game = apps.get_model("catalog", "Game")
    Developer = apps.get_model("catalog", "Developer")

    for game in Game.objects.all().iterator():
        name = (game.developer or "").strip()
        if not name:
            continue

        developer = Developer.objects.filter(name=name).first()
        if not developer:
            developer = Developer.objects.create(
                name=name,
                slug=_make_unique_slug(Developer, name),
            )

        game.developer_new_id = developer.id
        game.save(update_fields=["developer_new"])


def backwards_copy_developers(apps, schema_editor):
    Game = apps.get_model("catalog", "Game")

    for game in Game.objects.select_related("developer_new").all().iterator():
        game.developer = game.developer_new.name if game.developer_new_id else ""
        game.save(update_fields=["developer"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_game_detailed_description_game_developer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="developer_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="catalog.developer",
            ),
        ),
        migrations.RunPython(forwards_copy_developers, backwards_copy_developers),
        migrations.RemoveField(
            model_name="game",
            name="developer",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="developer_new",
            new_name="developer",
        ),
    ]
